name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: "21433038@life.hkbu.edu.hk"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "plzhang-chatbot"
          useforce: true,