name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
          uses: behe/heroku-build@v1
          with:
            app-name: "plzhang-chatbot"
            app-key: ${{secrets.HEROKU_API_KEY}}
            path: "optional-path-of-build-to-deploy"
